application:
  security:
    token_valid_second: 20
    signing_key: hillel144
springdoc:
  api-docs:
    path: /example/v3/api-docs
  swagger-ui:
    path: /swagger-ui/index.html

server:
  port: 8081
spring:
  main:
    allow-bean-definition-overriding: true
    mongodb:
      port: 27017
      database: db
#      username: ${MONGO_USER}
#      password: ${MONGO_PASSWORD}
