application:
  security:
    signing_key: hillel144
    token_valid_second: 20
server:
  port: 8081
spring:
  main:
    allow-bean-definition-overriding: true
    mongodb:
      port: 27017
      database: db
#      username: ${MONGO_USER}
#      password: ${MONGO_PASSWORD}
